#!/bin/bash
timestamp() {
	date +%s
}
. config/geiger.conf
if [ ! -f $rrdfile ]
then
	rrdtool create $rrdfile --step=1 --no-overwrite DS:cpm:GAUGE:1m:0:U \
		RRA:AVERAGE:0.5:1s:1w RRA:AVERAGE:0.5:5s:1M \
		RRA:AVERAGE:0.5:1m:1y
fi
last=$(timestamp)
stty -F $port $speed sane raw igncr
while read -r cpm < $port
do
	now=$(timestamp)
	if [ $now != $last ]
	then
		rrdtool update $rrdfile $now:$cpm
		last=$now
	fi
done
