#!/bin/bash
#
# graph -- geiger graph generator
# Copyright (C) 2015  abouvier <abouvier@student.42.fr>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config/geiger.conf"

rrdtool graph geiger.png --imgformat=PNG \
	--title="Geiger counter with $tube tube" \
	--start="-1hour" \
	--end="now" \
	--font="DEFAULT:0:monaco" \
	--vertical-label="µSv/h" \
	--width=720 \
	--height=240 \
	--lower-limit=0 \
	--units-exponent=0 \
	--left-axis-format="%.2lf" \
	--slope-mode \
	--watermark="$(date --rfc-2822)" \
	--border=0 \
	--color="BACK#924d8b" \
	--color="CANVAS#924d8b" \
	--color="FONT#ffffff" \
	--color="GRID#aea79f" \
	--color="MGRID#beb8b2" \
	--color="AXIS#beb8b2" \
	--color="ARROW#beb8b2" \
	--color="FRAME#333333" \
	DEF:cpm="$rrdfile":cpm:AVERAGE \
	CDEF:unit=cpm,"$factor",* \
	CDEF:trend=unit,240,TREND \
	VDEF:min=unit,MINIMUM \
	VDEF:avg=unit,AVERAGE \
	VDEF:max=unit,MAXIMUM \
	VDEF:last=unit,LAST \
	VDEF:tmin=trend,MINIMUM \
	VDEF:tavg=trend,AVERAGE \
	VDEF:tmax=trend,MAXIMUM \
	VDEF:tlast=trend,LAST \
	COMMENT:"\t\t" \
	COMMENT:"Min\t" \
	COMMENT:"Avg\t" \
	COMMENT:"Max\t" \
	COMMENT:"Last\l" \
	AREA:"unit#19b6eeaa" \
	LINE2:"unit#19b6ee":" μSv/h\t\t" \
	GPRINT:min:"%.3lf\t" \
	GPRINT:avg:"%.3lf\t" \
	GPRINT:max:"%.3lf\t" \
	GPRINT:last:"%.3lf\l" \
	LINE2:"trend#3fb24f":" Trend μSv/h\t" \
	GPRINT:tmin:"%.3lf\t" \
	GPRINT:tavg:"%.3lf\t" \
	GPRINT:tmax:"%.3lf\t" \
	GPRINT:tlast:"%.3lf\l" \
	LINE1:"avg#fc4949":" Average" \
	HRULE:"$(bc <<< "$alert*$factor")#dd4814: Alert\l"
