#!/bin/bash

. config/geiger.conf
duration=(hour day week month year)
trend=240

for i in ${duration[@]}; do
	rrdtool graph ${static}/cpm-${i}.png \
		--end="now" \
		--start="-1$i" \
		--title="$title ($i)" \
		--vertical-label="CPM" \
		--width=720 \
		--height=240 \
		--alt-y-grid \
		--slope-mode \
		--imgformat=PNG \
		--watermark="`date`" \
		--border=0 \
		--color="BACK#FFFFFF" \
		--color="GRID#666666" \
		--color="MGRID#333333" \
		--color="ARROW#000000" \
		DEF:cpm=$rrdfile:cpm:AVERAGE \
		VDEF:now=cpm,LAST \
		VDEF:min=cpm,MINIMUM \
		VDEF:avg=cpm,AVERAGE \
		VDEF:max=cpm,MAXIMUM \
		CDEF:trend=cpm,$trend,TREND \
		VDEF:tnow=trend,LAST \
		VDEF:tmin=trend,MINIMUM \
		VDEF:tavg=trend,AVERAGE \
		VDEF:tmax=trend,MAXIMUM \
		CDEF:usvh=cpm,0.0057,* \
		CDEF:msvy=usvh,24,366,0.001,*,*,* \
		CDEF:mremh=usvh,10,* \
		CDEF:remy=msvy,10,* \
		VDEF:uSv_h=usvh,AVERAGE \
		VDEF:mSv_y=msvy,AVERAGE \
		VDEF:mrem_h=mremh,AVERAGE \
		VDEF:rem_y=remy,AVERAGE \
		LINE2:"cpm#5bc0de":"CPM\t" \
		AREA:"cpm#5bc0de99" \
		GPRINT:now:"now\:%4.0lf" \
		GPRINT:min:"min\:%4.0lf" \
		GPRINT:avg:"avg\:%4.0lf" \
		GPRINT:max:"max\:%4.0lf" \
		COMMENT:"\t\t\tSievert\t" \
		GPRINT:uSv_h:"%3.3lf uSv/h" \
		GPRINT:mSv_y:"%3.3lf mSv/y\l" \
		LINE2:"trend#337AB7":"Trend\t" \
		GPRINT:tnow:"now\:%4.0lf" \
		GPRINT:tmin:"min\:%4.0lf" \
		GPRINT:tavg:"avg\:%4.0lf" \
		GPRINT:tmax:"max\:%4.0lf" \
		COMMENT:"\t\t\trem\t" \
		GPRINT:mrem_h:"%3.2lf mrem/h" \
		GPRINT:rem_y:"%3.3lf rem/y\l" \
		HRULE:"50#F0AD4E" \
		HRULE:"100#D9534F"
	rrdtool graph ${static}/sv-${i}.png \
		--end="now" \
		--start="-1$i" \
		--title="$title ($i)" \
		--vertical-label="Microsievert" \
		--width=720 \
		--height=240 \
		--alt-y-grid \
		--slope-mode \
		--imgformat=PNG \
		--watermark="`date`" \
		--border=0 \
		--color="BACK#FFFFFF" \
		--color="GRID#666666" \
		--color="MGRID#333333" \
		--color="ARROW#000000" \
		DEF:cpm=$rrdfile:cpm:AVERAGE \
		CDEF:usvh=cpm,0.0057,* \
		VDEF:now=usvh,LAST \
		VDEF:min=usvh,MINIMUM \
		VDEF:avg=usvh,AVERAGE \
		VDEF:max=usvh,MAXIMUM \
		CDEF:msvy=usvh,24,366,0.001,*,*,* \
		VDEF:year=msvy,AVERAGE \
		CDEF:trend=usvh,$trend,TREND \
		VDEF:tnow=trend,LAST \
		VDEF:tmin=trend,MINIMUM \
		VDEF:tavg=trend,AVERAGE \
		VDEF:tmax=trend,MAXIMUM \
		LINE2:"usvh#5bc0de":"Sievert\t" \
		AREA:"usvh#5bc0de99" \
		GPRINT:now:"now\: %2.3lf uSv/h" \
		GPRINT:min:"min\: %2.3lf uSv/h" \
		GPRINT:avg:"avg\: %2.3lf uSv/h" \
		GPRINT:max:"max\: %2.3lf uSv/h" \
		GPRINT:year:"year\: %3.3lf mSv/y\l" \
		LINE2:"trend#337AB7":"Trend\t\t" \
		GPRINT:tnow:"now\: %2.3lf uSv/h" \
		GPRINT:tmin:"min\: %2.3lf uSv/h" \
		GPRINT:tavg:"avg\: %2.3lf uSv/h" \
		GPRINT:tmax:"max\: %2.3lf uSv/h\l" \
		HRULE:"0.285#F0AD4E" \
		HRULE:"0.57#D9534F"
	trend=$((trend * 5))
done
