#!/bin/bash
#
# update -- Geiger update daemon
# Copyright (C) 2015  abouvier <abouvier@student.42.fr>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

timestamp () {
	date "$@" +%s
}

. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config/geiger.conf"

if [[ ! -e "$rrdfile" ]]
then
	rrdtool create "$rrdfile" --no-overwrite --step=1 DS:cpm:GAUGE:1m:0:U \
		RRA:AVERAGE:0.5:1s:1w \
		RRA:AVERAGE:0.5:5s:1M \
		RRA:AVERAGE:0.5:1m:1y
fi
last=$(timestamp --date=tomorrow)
stty -F "$port" "$speed" sane raw igncr
while read -r cpm
do
	now=$(timestamp)
	if (( "$now" > "$last" ))
	then
		rrdtool update "$rrdfile" "$now:$cpm"
	fi
	last="$now"
done < "$port"
